### PR TITLE
Fail and Win State Displays

### PR DESCRIPTION
**Pull request by EricESeitz**
This pull request does the following majority changes:

- On clicking a mine square, all mine squares show red, all remaining unclicked non-mine squares are 'clicked' to show full game board
- On clicking all non-mine squares, automatically win w/o manually flagging all squares

Required more testing, but on my end everything tests OK

### CODE REVIEW

**Comment by CompSciLauren** [comment]
When you lose the game, both the "game over" and "you win" pop-ups appear. I'm doing HW due at midnight like a bum right now or I'd try to find it in the code.... but atm not sure where it's happening

**Comment by EricESeitz** [comment]
> 
> 
> When you lose the game, both the "game over" and "you win" pop-ups appear. I'm doing HW due at midnight like a bum right now or I'd try to find it in the code.... but atm not sure where it's happening

Oops, you're right! For me "You Win!" flashed for a millisecond. Added a fix and repushed to it's branch. Test again if you have time?

**Comment by CompSciLauren** [comment]
> > When you lose the game, both the "game over" and "you win" pop-ups appear. I'm doing HW due at midnight like a bum right now or I'd try to find it in the code.... but atm not sure where it's happening
> 
> Oops, you're right! For me "You Win!" flashed for a millisecond. Added a fix and repushed to it's branch. Test again if you have time?

For me, the alert pops up, then I hit "ok" and the screen flashes quickly with the red squares displayed before immediately refreshing the page. Do you want to have the red squares and revealed squares appear before the alert pops up? That's not what's currently happening.

**Comment by EricESeitz** [comment]
> For me, the alert pops up, then I hit "ok" and the screen flashes quickly with the red squares displayed before immediately refreshing the page. Do you want to have the red squares and revealed squares appear before the alert pops up? That's not what's currently happening.

I need some more information, what exactly were you doing to get this end screen? Does the grid not change at all behind the pop-up?

**Comment by CompSciLauren** [comment]
> I need some more information, what exactly were you doing to get this end screen? Does the grid not change at all behind the pop-up?

I click a bomb. Next, an alert saying I lost appears. At this step, the screen still looks the same (without anything new being revealed or red color appearing). I hit "ok" on the popup. For a split second, I see the bomb squares are all revealed to be red. I can't tell if any other squares are revealed, but bombs are definitely turned to red. This happens extremely quickly and then the page is refreshed. Hope that makes more sense!

**Comment by EricESeitz** [comment]
> 
> 
> > I need some more information, what exactly were you doing to get this end screen? Does the grid not change at all behind the pop-up?
> 
> I click a bomb. Next, an alert saying I lost appears. At this step, the screen still looks the same (without anything new being revealed or red color appearing). I hit "ok" on the popup. For a split second, I see the bomb squares are all revealed to be red. I can't tell if any other squares are revealed, but bombs are definitely turned to red. This happens extremely quickly and then the page is refreshed. Hope that makes more sense!

Ok, what browser are you using?
Problem is I can't replicate this issue. On Firefox and Edge I see the squares update before the popup. The code itself runs the 'reveal' first and THEN issues the alert so I'm unsure why it would be different for you.

Dumb question, did you re-pull from the branch recently?

**Comment by CompSciLauren** [comment]
> Ok, what browser are you using?
> Problem is I can't replicate this issue. On Firefox and Edge I see the squares update before the popup. The code itself runs the 'reveal' first and THEN issues the alert so I'm unsure why it would be different for you.
> 
> Dumb question, did you re-pull from the branch recently?

I'm using Chrome and I did pull before testing this, it says I'm up to date.
I'll take a look once I get my homework done, feel free to step away from this for a bit, I know we want to get it merged asap. Or if we want to call it a bug, we could merge now and I can figure it out after my hw is done, whatever you think is best!

**Pull request merged**
